### ISSUE TITLE
Cannot install VCruntime 2015 & 2017 at the same time

### ISSUE THREAD

**Issue by axelrtgs** [chef-cookbooks/vcruntime#15]
> The Visual C++ 2017 RC Redistributable is a binary-compatible in-place upgrade of the Visual C++ 2015 Redistributable and shares the same registry keys. An application installer that follows the guidance, from the link above, will skip installation of the 2015 redistributable without error.

Due to the above you cannot install both 2015 and 2017 at the same time since 2017 is just an 'update' to 2015.

Opening only for tracking a PR is coming today which fixes this by not having both 2015 & 2017 in the default recipe.

**Comment by tas50** [comment]
Fix has been released
