### ISSUE TITLE
VC12 more recent version exist

### ISSUE THREAD

**Issue by lbn-chef-team** [chef-cookbooks/vcruntime#9]
Hello,

for VC12, it exist a more recent version:

https://support.microsoft.com/en-us/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package

12.0.40660.

actually the version used by cookbook is default['vcruntime']['vc12']['version'] = '12.0.30501'

Regards,

**Comment by tas50** [comment]
@lbn-chef-team If you could open a PR with the new release I'd gladly release that change.

**Comment by iennae** [comment]
@lbn-chef-team Thanks for your PR. I've merged and it's available in the latest version of the cookbook. For commits that are more than just attribute updates, please make sure you follow our DCO process and sign your commits as mentioned here: https://docs.chef.io/community_contributions.html.
